---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
  # annotations:
  #   fluxcd.io/automated: "true"
  #   filter.fluxcd.io/chart-image: glob:prod-*
spec:
  releaseName: minio
  interval: 1m
  chart:
    spec:
      chart: minio
      version: 8.0.7
      sourceRef: 
        kind: HelmRepository
        name: minio-repository
        # Optional, defaults to the namespace of the HelmRelease
        namespace: minio
  # chart:
  #   repository: https://helm.min.io/
  #   name: minio
  #   version: 8.0.7
  values:
    image:
      repository: minio/minio
      tag: RELEASE.2020-12-03T05-49-24Z
      pullPolicy: IfNotPresent
    accessKey: "qwermnbvpoiuyzxcvlkjhasdfwsxcftb"
    secretKey: "poPvfg35powe65wdv5jhQWd7wm9tfde"
    resources:
      requests:
        memory: 350Mi
        cpu: 100m
      limits:
        memory: 450Mi
        cpu: 150m
