---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio-repository
  namespace: minio
spec:
  # The interval at wich to check the upstream for updates
  interval: 1m
  # The repository URL, a valid URL contains at least a protocol and host
  url: https://helm.min.io/